setup slack notify action
brainly/action-slack-notificator pull request #1
Opened 2021-02-05 11:39 UTC by Fasosnql

2021-02-05 21:29 UTC, dsmileybrainly requested changes
I'd like to try a more functional setup as the data model for the functions seems well defined and lends itself to `pipe`.

2021-02-05 21:29 UTC, dsmileybrainly commented on src/index.ts
> +  } catch (e) {
is there anything we can/should do with the exception?

2021-02-05 21:29 UTC, dsmileybrainly commented on src/utils/getContextMessage.ts
> +export function getContextMessage({
If you wanted to take a functional approach you could use `export const getMessageContext = pipe(getContextMessage, buildContextMessage)` and rewrite them to accept a single parameter of type: `Block[]` where `Block` is:
```
type Block = {
   type: string;
   blocks: Element[]
}
type Element = {
   type: 'image' | 'text';
   text: string;
   image_url?:string;
   alt_text? string;
}
```
Then call:
```
getMessageContext({
userName,
  userUrl,
  avatarUrl,
  message,
  messageUrl,
  pullRequestData
});
```
These functions could one day be useful in an SDK that would allow you to compose actions quickly. So not using direct usage (ie not calling `text: buildContextMessage({message, messageUrl, pullRequestData})`) promotes composition.

2021-02-05 21:29 UTC, dsmileybrainly commented on src/utils/getInitialMessage.ts
> +export function getInitialMessage(message?: string) {
Same comment as above regarding refactoring the method signature to support `pipe`.

2021-02-05 21:29 UTC, dsmileybrainly commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Can you set the setting to collapse this file.

2021-02-08 13:16 UTC, Fasosnql commented on src/index.ts
> +  } catch (e) {
we can throw it on the console and thats it, It's gonna be public action so we can't do any request to sentry etc.

2021-02-08 19:42 UTC, dsmileybrainly approved these changes

2021-02-10 09:28 UTC, maciekbb requested changes

2021-02-10 09:28 UTC, maciekbb commented on src/utils/getContextMessage.ts
> +export function getContextUserInfo({
Probably this should not be exported.

2021-02-10 09:28 UTC, maciekbb commented on src/types/block.ts
> +};
Formatting feels odd here, probably prettier is needed :)

2021-02-10 09:28 UTC, maciekbb commented on src/utils/getContextMessage.ts
> +export const getContextMessage: (props: ContextMessageProps) => Block[] = pipe(
Frankly I'd break it down further, e.g.

```
pipe(
  extractDataFromContext,
  parsePRData,
  appendUserDataBlock,
  appendPRMessageBlock,
)
```

Right now this does not feel like a "pipe"

2021-02-10 15:24 UTC, radekwarisch commented on action.yml
> +    description: 'Data of pull request which will be attach to message context in shape ot {title: string, url: string, user: {url, login, avatarUrl}}}'
shape of

2021-02-10 15:24 UTC, radekwarisch commented on src/index.ts
> +main().catch(err => `slack notificator action failed: ${err}`);
could you parse an error inside main()?

2021-02-10 15:24 UTC, radekwarisch commented on src/utils/getContextMessage.ts
> +  return [
I believe you could put return in `finally`, It would be more readable then

2021-02-10 15:24 UTC, radekwarisch commented on src/utils/getInitialMessage.ts
> +  if (!message) {
```
pipe(
 ifElse(
 isNull,
 () => ({blocks: []}),
  tryCatch(
    bind(JSON.parse, JSON),
    () => ({blocks: [
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: message
          }
        }
      ]})
  )
 )
)
```

2021-02-11 12:46 UTC, Fasosnql commented on src/utils/getContextMessage.ts
> +  return [
Hmm, I'm not sure if this is good pattern, I always try to avoid it because finally will rewrite what I will do in try, catch block. I realise that in that case it will work but even my IDE always complain about it:
![image](https://user-images.githubusercontent.com/13320330/107638075-6402b200-6c6f-11eb-8eda-94ce83e73495.png)

2021-02-11 14:24 UTC, dsmileybrainly approved these changes

2021-02-12 09:24 UTC, maciekbb approved these changes

2021-02-12 09:24 UTC, merged